baseurl = "https://sybrandt.com/kayleen/"
title = "Kayleen Vacco Sybrandt"
author = "Justin Sybrandt"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
description = "A memorial page for Kayleen Vacco Sybrandt"

pygmentsstyle       = "bw"
pygmentscodefences  = true

assetDir = "static"
timeout = "120s"

[params]
  sitename = "In Memory of Kayleen Vacco Sybrandt"
  description = "1943-2022"
  disableWebFonts = false

[[menu.main]]
    name = "Justin's Message"
    url  = "/"
    weight = 1
[[menu.main]]
    name = "Larry's Message"
    url  = "/larry"
    weight = 2
[[menu.main]]
    name = "Jennifer's Message"
    url  = "/jennifer"
    weight = 3
