baseurl = "https://sybrandt.com/kayleen/"
title = "Kayleen Vacco Sybrandt"
author = "Justin Sybrandt"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
description = "A memorial page for Kayleen Vacco Sybrandt"

pygmentsstyle       = "bw"
pygmentscodefences  = true

assetDir = "static"
timeout = "120s"

[params]
  sitename = "In Loving Memory of Kayleen Vacco Sybrandt"
  description = "1943-2022"
  disableWebFonts = false

# [[menu.main]]
#     name = "About"
#     url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
# [[menu.main]]
#     name = "Projects"
#     url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"
# [[menu.main]]
#     name = "Resume"
#     url  = "https://github.com/davidhampgonsalves/hugo-black-and-light-theme"

